name: enterprise-ci-deps (OSV)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  osv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google/osv-scanner-action@v2
        with:
          scan-args: |-
            -r
            .
    if: ${{ !(((github.event_name == 'push' && github.ref != 'refs/heads/main' 
      && (contains(github.event.head_commit.message, '[skip ci]') || 
      contains(github.event.head_commit.message, '[ci skip]')))) || 
      ((github.event_name == 'pull_request' && 
      (contains(github.event.pull_request.title, '[skip ci]') || 
      contains(github.event.pull_request.title, '[ci skip]')))))) }}
